name: Deploy to EC2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Dockerized Application
      run: |
        cd $GITHUB_WORKSPACE
        # Check if there are any running containers
        if [ "$(docker-compose ps -q)" ]; then
          echo "Docker Compose is running. Bringing it down..."
          docker-compose down
        else
          echo "Docker Compose is not running."
        fi
        # Bring the application up
        docker-compose up -d
